/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.ui;

import com.google.inject.Injector;
import mde.pauline.metaheres.ui.internal.MetaheresActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MetaheresExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MetaheresActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MetaheresActivator activator = MetaheresActivator.getInstance();
		return activator != null ? activator.getInjector(MetaheresActivator.MDE_PAULINE_METAHERES_METAHERES) : null;
	}

}
