/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MetaheresAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mde/pauline/metaheres/parser/antlr/internal/InternalMetaheres.tokens");
	}
}
