/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.ui.tests;

import com.google.inject.Injector;
import mde.pauline.metaheres.metaheres.ui.internal.MetaheresActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MetaheresActivator.getInstance().getInjector("mde.pauline.metaheres.My");
	}

}
