/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mde.pauline.metaheres.MetaheresRuntimeModule;
import mde.pauline.metaheres.MetaheresStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MetaheresIdeSetup extends MetaheresStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MetaheresRuntimeModule(), new MetaheresIdeModule()));
	}
	
}
