/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyUiModule extends AbstractMyUiModule {

	public MyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
