/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyScopeProvider extends DelegatingScopeProvider {
}
