/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MetaheresStandaloneSetup extends MetaheresStandaloneSetupGenerated {

	public static void doSetup() {
		new MetaheresStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
