/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaheresRuntimeModule extends AbstractMetaheresRuntimeModule {
}
