/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SServiceNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.SServiceName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cServiceconfigAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cServiceconfigServiceConfigParserRuleCall_2_0 = (RuleCall)cServiceconfigAssignment_2.eContents().get(0);
		
		//SServiceName returns ServiceName:
		//    name=EString
		//    ':'
		//    serviceconfig=ServiceConfig;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString
		//':'
		//serviceconfig=ServiceConfig
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//serviceconfig=ServiceConfig
		public Assignment getServiceconfigAssignment_2() { return cServiceconfigAssignment_2; }
		
		//ServiceConfig
		public RuleCall getServiceconfigServiceConfigParserRuleCall_2_0() { return cServiceconfigServiceConfigParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ServiceConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ServiceConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cClosesOnPublicHolidaysAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cClosesOnPublicHolidaysFermeLesJoursFeriesKeyword_0_0 = (Keyword)cClosesOnPublicHolidaysAssignment_0.eContents().get(0);
		private final Assignment cInventoryIsPublicAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cInventoryIsPublicInventairePublicKeyword_1_0 = (Keyword)cInventoryIsPublicAssignment_1.eContents().get(0);
		private final Assignment cHasChartAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasChartCharteDUtilisationVisibleKeyword_2_0 = (Keyword)cHasChartAssignment_2.eContents().get(0);
		private final Assignment cCountInBusinessDaysAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cCountInBusinessDaysCompteEnJoursOuvrablesKeyword_3_0 = (Keyword)cCountInBusinessDaysAssignment_3.eContents().get(0);
		private final Keyword cPaysKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCountryAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCountryCountryParserRuleCall_6_0 = (RuleCall)cCountryAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCountryAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cCountryCountryParserRuleCall_7_1_0 = (RuleCall)cCountryAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPaiementsProposesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Assignment cPricingsystemAssignment_8_3 = (Assignment)cGroup_8.eContents().get(3);
		private final CrossReference cPricingsystemPricingSystemCrossReference_8_3_0 = (CrossReference)cPricingsystemAssignment_8_3.eContents().get(0);
		private final RuleCall cPricingsystemPricingSystemEStringParserRuleCall_8_3_0_1 = (RuleCall)cPricingsystemPricingSystemCrossReference_8_3_0.eContents().get(1);
		private final Group cGroup_8_4 = (Group)cGroup_8.eContents().get(4);
		private final Keyword cCommaKeyword_8_4_0 = (Keyword)cGroup_8_4.eContents().get(0);
		private final Assignment cPricingsystemAssignment_8_4_1 = (Assignment)cGroup_8_4.eContents().get(1);
		private final CrossReference cPricingsystemPricingSystemCrossReference_8_4_1_0 = (CrossReference)cPricingsystemAssignment_8_4_1.eContents().get(0);
		private final RuleCall cPricingsystemPricingSystemEStringParserRuleCall_8_4_1_0_1 = (RuleCall)cPricingsystemPricingSystemCrossReference_8_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLanguesKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cColonKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftParenthesisKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cLanguageAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cLanguageLanguageParserRuleCall_13_0 = (RuleCall)cLanguageAssignment_13.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cCommaKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cLanguageAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cLanguageLanguageParserRuleCall_14_1_0 = (RuleCall)cLanguageAssignment_14_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cConfigurationReservationsKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cColonKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cReservationsconfigAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cReservationsconfigReservationsConfigParserRuleCall_18_0 = (RuleCall)cReservationsconfigAssignment_18.eContents().get(0);
		private final Keyword cConfigurationRessourcesKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cColonKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cResourcesconfigAssignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cResourcesconfigResourcesConfigParserRuleCall_21_0 = (RuleCall)cResourcesconfigAssignment_21.eContents().get(0);
		private final Group cGroup_22 = (Group)cGroup.eContents().get(22);
		private final Keyword cCommaKeyword_22_0 = (Keyword)cGroup_22.eContents().get(0);
		private final Assignment cResourcesconfigAssignment_22_1 = (Assignment)cGroup_22.eContents().get(1);
		private final RuleCall cResourcesconfigResourcesConfigParserRuleCall_22_1_0 = (RuleCall)cResourcesconfigAssignment_22_1.eContents().get(0);
		private final Group cGroup_23 = (Group)cGroup.eContents().get(23);
		private final Keyword cLotsconfigKeyword_23_0 = (Keyword)cGroup_23.eContents().get(0);
		private final Keyword cColonKeyword_23_1 = (Keyword)cGroup_23.eContents().get(1);
		private final Assignment cLotsconfigAssignment_23_2 = (Assignment)cGroup_23.eContents().get(2);
		private final RuleCall cLotsconfigLotsConfigParserRuleCall_23_2_0 = (RuleCall)cLotsconfigAssignment_23_2.eContents().get(0);
		
		//ServiceConfig returns ServiceConfig:
		//    (closesOnPublicHolidays?='ferme-les-jours-feries')?
		//    (inventoryIsPublic?='inventaire-public')?
		//    (hasChart?='charte-d-utilisation-visible')?
		//    (countInBusinessDays?='compte-en-jours-ouvrables')?
		//    'pays'':' country+=Country ( "," country+=Country)*
		//    ('paiements-proposes' ':' '(' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )? ')'
		//    'langues' ':' '(' language+=Language ( "," language+=Language)* ')'
		//    'configuration-reservations' ':' reservationsconfig=ReservationsConfig
		//    'configuration-ressources' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
		//    ('lotsconfig' ':' lotsconfig=LotsConfig)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(closesOnPublicHolidays?='ferme-les-jours-feries')?
		//(inventoryIsPublic?='inventaire-public')?
		//(hasChart?='charte-d-utilisation-visible')?
		//(countInBusinessDays?='compte-en-jours-ouvrables')?
		//'pays'':' country+=Country ( "," country+=Country)*
		//('paiements-proposes' ':' '(' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )? ')'
		//'langues' ':' '(' language+=Language ( "," language+=Language)* ')'
		//'configuration-reservations' ':' reservationsconfig=ReservationsConfig
		//'configuration-ressources' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
		//('lotsconfig' ':' lotsconfig=LotsConfig)?
		public Group getGroup() { return cGroup; }
		
		//(closesOnPublicHolidays?='ferme-les-jours-feries')?
		public Assignment getClosesOnPublicHolidaysAssignment_0() { return cClosesOnPublicHolidaysAssignment_0; }
		
		//'ferme-les-jours-feries'
		public Keyword getClosesOnPublicHolidaysFermeLesJoursFeriesKeyword_0_0() { return cClosesOnPublicHolidaysFermeLesJoursFeriesKeyword_0_0; }
		
		//(inventoryIsPublic?='inventaire-public')?
		public Assignment getInventoryIsPublicAssignment_1() { return cInventoryIsPublicAssignment_1; }
		
		//'inventaire-public'
		public Keyword getInventoryIsPublicInventairePublicKeyword_1_0() { return cInventoryIsPublicInventairePublicKeyword_1_0; }
		
		//(hasChart?='charte-d-utilisation-visible')?
		public Assignment getHasChartAssignment_2() { return cHasChartAssignment_2; }
		
		//'charte-d-utilisation-visible'
		public Keyword getHasChartCharteDUtilisationVisibleKeyword_2_0() { return cHasChartCharteDUtilisationVisibleKeyword_2_0; }
		
		//(countInBusinessDays?='compte-en-jours-ouvrables')?
		public Assignment getCountInBusinessDaysAssignment_3() { return cCountInBusinessDaysAssignment_3; }
		
		//'compte-en-jours-ouvrables'
		public Keyword getCountInBusinessDaysCompteEnJoursOuvrablesKeyword_3_0() { return cCountInBusinessDaysCompteEnJoursOuvrablesKeyword_3_0; }
		
		//'pays'
		public Keyword getPaysKeyword_4() { return cPaysKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//country+=Country
		public Assignment getCountryAssignment_6() { return cCountryAssignment_6; }
		
		//Country
		public RuleCall getCountryCountryParserRuleCall_6_0() { return cCountryCountryParserRuleCall_6_0; }
		
		//( "," country+=Country)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//country+=Country
		public Assignment getCountryAssignment_7_1() { return cCountryAssignment_7_1; }
		
		//Country
		public RuleCall getCountryCountryParserRuleCall_7_1_0() { return cCountryCountryParserRuleCall_7_1_0; }
		
		//('paiements-proposes' ':' '(' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'paiements-proposes'
		public Keyword getPaiementsProposesKeyword_8_0() { return cPaiementsProposesKeyword_8_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_8_2() { return cLeftParenthesisKeyword_8_2; }
		
		//pricingsystem+=[PricingSystem|EString]
		public Assignment getPricingsystemAssignment_8_3() { return cPricingsystemAssignment_8_3; }
		
		//[PricingSystem|EString]
		public CrossReference getPricingsystemPricingSystemCrossReference_8_3_0() { return cPricingsystemPricingSystemCrossReference_8_3_0; }
		
		//EString
		public RuleCall getPricingsystemPricingSystemEStringParserRuleCall_8_3_0_1() { return cPricingsystemPricingSystemEStringParserRuleCall_8_3_0_1; }
		
		//( "," pricingsystem+=[PricingSystem|EString])*
		public Group getGroup_8_4() { return cGroup_8_4; }
		
		//","
		public Keyword getCommaKeyword_8_4_0() { return cCommaKeyword_8_4_0; }
		
		//pricingsystem+=[PricingSystem|EString]
		public Assignment getPricingsystemAssignment_8_4_1() { return cPricingsystemAssignment_8_4_1; }
		
		//[PricingSystem|EString]
		public CrossReference getPricingsystemPricingSystemCrossReference_8_4_1_0() { return cPricingsystemPricingSystemCrossReference_8_4_1_0; }
		
		//EString
		public RuleCall getPricingsystemPricingSystemEStringParserRuleCall_8_4_1_0_1() { return cPricingsystemPricingSystemEStringParserRuleCall_8_4_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
		
		//'langues'
		public Keyword getLanguesKeyword_10() { return cLanguesKeyword_10; }
		
		//':'
		public Keyword getColonKeyword_11() { return cColonKeyword_11; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_12() { return cLeftParenthesisKeyword_12; }
		
		//language+=Language
		public Assignment getLanguageAssignment_13() { return cLanguageAssignment_13; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_13_0() { return cLanguageLanguageParserRuleCall_13_0; }
		
		//( "," language+=Language)*
		public Group getGroup_14() { return cGroup_14; }
		
		//","
		public Keyword getCommaKeyword_14_0() { return cCommaKeyword_14_0; }
		
		//language+=Language
		public Assignment getLanguageAssignment_14_1() { return cLanguageAssignment_14_1; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_14_1_0() { return cLanguageLanguageParserRuleCall_14_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_15() { return cRightParenthesisKeyword_15; }
		
		//'configuration-reservations'
		public Keyword getConfigurationReservationsKeyword_16() { return cConfigurationReservationsKeyword_16; }
		
		//':'
		public Keyword getColonKeyword_17() { return cColonKeyword_17; }
		
		//reservationsconfig=ReservationsConfig
		public Assignment getReservationsconfigAssignment_18() { return cReservationsconfigAssignment_18; }
		
		//ReservationsConfig
		public RuleCall getReservationsconfigReservationsConfigParserRuleCall_18_0() { return cReservationsconfigReservationsConfigParserRuleCall_18_0; }
		
		//'configuration-ressources'
		public Keyword getConfigurationRessourcesKeyword_19() { return cConfigurationRessourcesKeyword_19; }
		
		//':'
		public Keyword getColonKeyword_20() { return cColonKeyword_20; }
		
		//resourcesconfig+=ResourcesConfig
		public Assignment getResourcesconfigAssignment_21() { return cResourcesconfigAssignment_21; }
		
		//ResourcesConfig
		public RuleCall getResourcesconfigResourcesConfigParserRuleCall_21_0() { return cResourcesconfigResourcesConfigParserRuleCall_21_0; }
		
		//( "," resourcesconfig+=ResourcesConfig)*
		public Group getGroup_22() { return cGroup_22; }
		
		//","
		public Keyword getCommaKeyword_22_0() { return cCommaKeyword_22_0; }
		
		//resourcesconfig+=ResourcesConfig
		public Assignment getResourcesconfigAssignment_22_1() { return cResourcesconfigAssignment_22_1; }
		
		//ResourcesConfig
		public RuleCall getResourcesconfigResourcesConfigParserRuleCall_22_1_0() { return cResourcesconfigResourcesConfigParserRuleCall_22_1_0; }
		
		//('lotsconfig' ':' lotsconfig=LotsConfig)?
		public Group getGroup_23() { return cGroup_23; }
		
		//'lotsconfig'
		public Keyword getLotsconfigKeyword_23_0() { return cLotsconfigKeyword_23_0; }
		
		//':'
		public Keyword getColonKeyword_23_1() { return cColonKeyword_23_1; }
		
		//lotsconfig=LotsConfig
		public Assignment getLotsconfigAssignment_23_2() { return cLotsconfigAssignment_23_2; }
		
		//LotsConfig
		public RuleCall getLotsconfigLotsConfigParserRuleCall_23_2_0() { return cLotsconfigLotsConfigParserRuleCall_23_2_0; }
	}
	public class EBooleanObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EBooleanObject");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBooleanObject returns ecore::EBooleanObject:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class LanguageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Language");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLanguageAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Language returns Language:
		//    {Language}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Language}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Language}
		public Action getLanguageAction_0() { return cLanguageAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class ReservationsConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ReservationsConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHasMoveOutCheckAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHasMoveOutCheckEtatDesLieuxSortieKeyword_0_0 = (Keyword)cHasMoveOutCheckAssignment_0.eContents().get(0);
		private final Assignment cHasMoveInCheckAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasMoveInCheckEtatDesLieuxRetourKeyword_1_0 = (Keyword)cHasMoveInCheckAssignment_1.eContents().get(0);
		private final Keyword cAvanceMinimumEtMaximumReservationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMinRequestAdvanceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMinRequestAdvanceEIntParserRuleCall_4_0 = (RuleCall)cMinRequestAdvanceAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMaxRequestAdvanceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMaxRequestAdvanceEIntParserRuleCall_6_0 = (RuleCall)cMaxRequestAdvanceAssignment_6.eContents().get(0);
		private final Keyword cStatutsDesDemandesKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cColonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cStatuslistAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cStatuslistStatusListParserRuleCall_9_0 = (RuleCall)cStatuslistAssignment_9.eContents().get(0);
		
		//ReservationsConfig returns ReservationsConfig:
		//    hasMoveOutCheck?='etat-des-lieux-sortie'
		//    (hasMoveInCheck?='etat-des-lieux-retour')?
		//        'avance-minimum-et-maximum-reservation' ':' minRequestAdvance=EInt ',' maxRequestAdvance=EInt
		//        'statuts-des-demandes' ':' statuslist=StatusList
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//hasMoveOutCheck?='etat-des-lieux-sortie'
		//(hasMoveInCheck?='etat-des-lieux-retour')?
		//    'avance-minimum-et-maximum-reservation' ':' minRequestAdvance=EInt ',' maxRequestAdvance=EInt
		//    'statuts-des-demandes' ':' statuslist=StatusList
		public Group getGroup() { return cGroup; }
		
		//hasMoveOutCheck?='etat-des-lieux-sortie'
		public Assignment getHasMoveOutCheckAssignment_0() { return cHasMoveOutCheckAssignment_0; }
		
		//'etat-des-lieux-sortie'
		public Keyword getHasMoveOutCheckEtatDesLieuxSortieKeyword_0_0() { return cHasMoveOutCheckEtatDesLieuxSortieKeyword_0_0; }
		
		//(hasMoveInCheck?='etat-des-lieux-retour')?
		public Assignment getHasMoveInCheckAssignment_1() { return cHasMoveInCheckAssignment_1; }
		
		//'etat-des-lieux-retour'
		public Keyword getHasMoveInCheckEtatDesLieuxRetourKeyword_1_0() { return cHasMoveInCheckEtatDesLieuxRetourKeyword_1_0; }
		
		//'avance-minimum-et-maximum-reservation'
		public Keyword getAvanceMinimumEtMaximumReservationKeyword_2() { return cAvanceMinimumEtMaximumReservationKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//minRequestAdvance=EInt
		public Assignment getMinRequestAdvanceAssignment_4() { return cMinRequestAdvanceAssignment_4; }
		
		//EInt
		public RuleCall getMinRequestAdvanceEIntParserRuleCall_4_0() { return cMinRequestAdvanceEIntParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//maxRequestAdvance=EInt
		public Assignment getMaxRequestAdvanceAssignment_6() { return cMaxRequestAdvanceAssignment_6; }
		
		//EInt
		public RuleCall getMaxRequestAdvanceEIntParserRuleCall_6_0() { return cMaxRequestAdvanceEIntParserRuleCall_6_0; }
		
		//'statuts-des-demandes'
		public Keyword getStatutsDesDemandesKeyword_7() { return cStatutsDesDemandesKeyword_7; }
		
		//':'
		public Keyword getColonKeyword_8() { return cColonKeyword_8; }
		
		//statuslist=StatusList
		public Assignment getStatuslistAssignment_9() { return cStatuslistAssignment_9; }
		
		//StatusList
		public RuleCall getStatuslistStatusListParserRuleCall_9_0() { return cStatuslistStatusListParserRuleCall_9_0; }
	}
	public class CountryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Country");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageLanguageParserRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTarificationKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPricingsystemAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPricingsystemPricingSystemParserRuleCall_6_0 = (RuleCall)cPricingsystemAssignment_6.eContents().get(0);
		
		//Country returns Country:
		//    name=EString ':'
		//        language=Language ','
		//        'tarification' ':' pricingsystem=PricingSystem
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ':'
		//    language=Language ','
		//    'tarification' ':' pricingsystem=PricingSystem
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//language=Language
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_2_0() { return cLanguageLanguageParserRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//'tarification'
		public Keyword getTarificationKeyword_4() { return cTarificationKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//pricingsystem=PricingSystem
		public Assignment getPricingsystemAssignment_6() { return cPricingsystemAssignment_6; }
		
		//PricingSystem
		public RuleCall getPricingsystemPricingSystemParserRuleCall_6_0() { return cPricingsystemPricingSystemParserRuleCall_6_0; }
	}
	public class ResourcesConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ResourcesConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHasImageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasImageAvecIllustrationKeyword_1_0 = (Keyword)cHasImageAssignment_1.eContents().get(0);
		private final Assignment cHasOneStockPerSlotAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasOneStockPerSlotUnStockParOuvertureKeyword_2_0 = (Keyword)cHasOneStockPerSlotAssignment_2.eContents().get(0);
		private final Assignment cIsConsumableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cIsConsumableTypeConsommableKeyword_3_0 = (Keyword)cIsConsumableAssignment_3.eContents().get(0);
		private final Assignment cIsLoanAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cIsLoanEmpruntAvecRetourKeyword_4_0 = (Keyword)cIsLoanAssignment_4.eContents().get(0);
		private final Assignment cIsChargedAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cIsChargedPayantKeyword_5_0 = (Keyword)cIsChargedAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ResourcesConfig returns ResourcesConfig:
		//    '('
		//    (hasImage?='avec-illustration')?
		//    (hasOneStockPerSlot?='un-stock-par-ouverture')?
		//    (isConsumable?='type-consommable')?
		//    (isLoan?='emprunt-avec-retour')?
		//    (isCharged?='payant')?
		//    ')'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'('
		//(hasImage?='avec-illustration')?
		//(hasOneStockPerSlot?='un-stock-par-ouverture')?
		//(isConsumable?='type-consommable')?
		//(isLoan?='emprunt-avec-retour')?
		//(isCharged?='payant')?
		//')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//(hasImage?='avec-illustration')?
		public Assignment getHasImageAssignment_1() { return cHasImageAssignment_1; }
		
		//'avec-illustration'
		public Keyword getHasImageAvecIllustrationKeyword_1_0() { return cHasImageAvecIllustrationKeyword_1_0; }
		
		//(hasOneStockPerSlot?='un-stock-par-ouverture')?
		public Assignment getHasOneStockPerSlotAssignment_2() { return cHasOneStockPerSlotAssignment_2; }
		
		//'un-stock-par-ouverture'
		public Keyword getHasOneStockPerSlotUnStockParOuvertureKeyword_2_0() { return cHasOneStockPerSlotUnStockParOuvertureKeyword_2_0; }
		
		//(isConsumable?='type-consommable')?
		public Assignment getIsConsumableAssignment_3() { return cIsConsumableAssignment_3; }
		
		//'type-consommable'
		public Keyword getIsConsumableTypeConsommableKeyword_3_0() { return cIsConsumableTypeConsommableKeyword_3_0; }
		
		//(isLoan?='emprunt-avec-retour')?
		public Assignment getIsLoanAssignment_4() { return cIsLoanAssignment_4; }
		
		//'emprunt-avec-retour'
		public Keyword getIsLoanEmpruntAvecRetourKeyword_4_0() { return cIsLoanEmpruntAvecRetourKeyword_4_0; }
		
		//(isCharged?='payant')?
		public Assignment getIsChargedAssignment_5() { return cIsChargedAssignment_5; }
		
		//'payant'
		public Keyword getIsChargedPayantKeyword_5_0() { return cIsChargedPayantKeyword_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class LotsConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.LotsConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLotsConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHasImageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasImageAvecIllustrationKeyword_2_0 = (Keyword)cHasImageAssignment_2.eContents().get(0);
		private final Assignment cHasOneStockPerSlotAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cHasOneStockPerSlotUnStockParOuvertureKeyword_3_0 = (Keyword)cHasOneStockPerSlotAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//LotsConfig returns LotsConfig:
		//    {LotsConfig} '('
		//    (hasImage?='avec-illustration')?
		//    (hasOneStockPerSlot?='un-stock-par-ouverture')?
		//    ')'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{LotsConfig} '('
		//(hasImage?='avec-illustration')?
		//(hasOneStockPerSlot?='un-stock-par-ouverture')?
		//')'
		public Group getGroup() { return cGroup; }
		
		//{LotsConfig}
		public Action getLotsConfigAction_0() { return cLotsConfigAction_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//(hasImage?='avec-illustration')?
		public Assignment getHasImageAssignment_2() { return cHasImageAssignment_2; }
		
		//'avec-illustration'
		public Keyword getHasImageAvecIllustrationKeyword_2_0() { return cHasImageAvecIllustrationKeyword_2_0; }
		
		//(hasOneStockPerSlot?='un-stock-par-ouverture')?
		public Assignment getHasOneStockPerSlotAssignment_3() { return cHasOneStockPerSlotAssignment_3; }
		
		//'un-stock-par-ouverture'
		public Keyword getHasOneStockPerSlotUnStockParOuvertureKeyword_3_0() { return cHasOneStockPerSlotUnStockParOuvertureKeyword_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class PricingSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.PricingSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDeviseKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCurrencyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCurrencyEStringParserRuleCall_4_0 = (RuleCall)cCurrencyAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cSystemeComptableKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTaxSystemAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTaxSystemEStringParserRuleCall_8_0 = (RuleCall)cTaxSystemAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//PricingSystem returns PricingSystem:
		//    name=EString '('
		//    'devise' ':' currency=EString ','
		//    'systeme-comptable' ':' taxSystem=EString
		//    ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString '('
		//'devise' ':' currency=EString ','
		//'systeme-comptable' ':' taxSystem=EString
		//')'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//'devise'
		public Keyword getDeviseKeyword_2() { return cDeviseKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//currency=EString
		public Assignment getCurrencyAssignment_4() { return cCurrencyAssignment_4; }
		
		//EString
		public RuleCall getCurrencyEStringParserRuleCall_4_0() { return cCurrencyEStringParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//'systeme-comptable'
		public Keyword getSystemeComptableKeyword_6() { return cSystemeComptableKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//taxSystem=EString
		public Assignment getTaxSystemAssignment_8() { return cTaxSystemAssignment_8; }
		
		//EString
		public RuleCall getTaxSystemEStringParserRuleCall_8_0() { return cTaxSystemEStringParserRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class StatusListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.StatusList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStatusAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStatusStatusParserRuleCall_1_0 = (RuleCall)cStatusAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cStatusAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStatusStatusParserRuleCall_2_1_0 = (RuleCall)cStatusAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//StatusList returns StatusList:
		//        '(' status+=Status ( "," status+=Status)* ')'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' status+=Status ( "," status+=Status)* ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//status+=Status
		public Assignment getStatusAssignment_1() { return cStatusAssignment_1; }
		
		//Status
		public RuleCall getStatusStatusParserRuleCall_1_0() { return cStatusStatusParserRuleCall_1_0; }
		
		//( "," status+=Status)*
		public Group getGroup_2() { return cGroup_2; }
		
		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//status+=Status
		public Assignment getStatusAssignment_2_1() { return cStatusAssignment_2_1; }
		
		//Status
		public RuleCall getStatusStatusParserRuleCall_2_1_0() { return cStatusStatusParserRuleCall_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class StatusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Status");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStatusAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Status returns Status:
		//    {Status}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Status}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Status}
		public Action getStatusAction_0() { return cStatusAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	
	
	private final SServiceNameElements pSServiceName;
	private final EStringElements pEString;
	private final ServiceConfigElements pServiceConfig;
	private final EBooleanObjectElements pEBooleanObject;
	private final LanguageElements pLanguage;
	private final ReservationsConfigElements pReservationsConfig;
	private final CountryElements pCountry;
	private final ResourcesConfigElements pResourcesConfig;
	private final LotsConfigElements pLotsConfig;
	private final PricingSystemElements pPricingSystem;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final StatusListElements pStatusList;
	private final StatusElements pStatus;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSServiceName = new SServiceNameElements();
		this.pEString = new EStringElements();
		this.pServiceConfig = new ServiceConfigElements();
		this.pEBooleanObject = new EBooleanObjectElements();
		this.pLanguage = new LanguageElements();
		this.pReservationsConfig = new ReservationsConfigElements();
		this.pCountry = new CountryElements();
		this.pResourcesConfig = new ResourcesConfigElements();
		this.pLotsConfig = new LotsConfigElements();
		this.pPricingSystem = new PricingSystemElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pStatusList = new StatusListElements();
		this.pStatus = new StatusElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mde.pauline.metaheres.My".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SServiceName returns ServiceName:
	//    name=EString
	//    ':'
	//    serviceconfig=ServiceConfig;
	public SServiceNameElements getSServiceNameAccess() {
		return pSServiceName;
	}
	
	public ParserRule getSServiceNameRule() {
		return getSServiceNameAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ServiceConfig returns ServiceConfig:
	//    (closesOnPublicHolidays?='ferme-les-jours-feries')?
	//    (inventoryIsPublic?='inventaire-public')?
	//    (hasChart?='charte-d-utilisation-visible')?
	//    (countInBusinessDays?='compte-en-jours-ouvrables')?
	//    'pays'':' country+=Country ( "," country+=Country)*
	//    ('paiements-proposes' ':' '(' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )? ')'
	//    'langues' ':' '(' language+=Language ( "," language+=Language)* ')'
	//    'configuration-reservations' ':' reservationsconfig=ReservationsConfig
	//    'configuration-ressources' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
	//    ('lotsconfig' ':' lotsconfig=LotsConfig)?
	//;
	public ServiceConfigElements getServiceConfigAccess() {
		return pServiceConfig;
	}
	
	public ParserRule getServiceConfigRule() {
		return getServiceConfigAccess().getRule();
	}
	
	//EBooleanObject returns ecore::EBooleanObject:
	//    'true' | 'false';
	public EBooleanObjectElements getEBooleanObjectAccess() {
		return pEBooleanObject;
	}
	
	public ParserRule getEBooleanObjectRule() {
		return getEBooleanObjectAccess().getRule();
	}
	
	//Language returns Language:
	//    {Language}
	//    name=EString;
	public LanguageElements getLanguageAccess() {
		return pLanguage;
	}
	
	public ParserRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}
	
	//ReservationsConfig returns ReservationsConfig:
	//    hasMoveOutCheck?='etat-des-lieux-sortie'
	//    (hasMoveInCheck?='etat-des-lieux-retour')?
	//        'avance-minimum-et-maximum-reservation' ':' minRequestAdvance=EInt ',' maxRequestAdvance=EInt
	//        'statuts-des-demandes' ':' statuslist=StatusList
	//    ;
	public ReservationsConfigElements getReservationsConfigAccess() {
		return pReservationsConfig;
	}
	
	public ParserRule getReservationsConfigRule() {
		return getReservationsConfigAccess().getRule();
	}
	
	//Country returns Country:
	//    name=EString ':'
	//        language=Language ','
	//        'tarification' ':' pricingsystem=PricingSystem
	//;
	public CountryElements getCountryAccess() {
		return pCountry;
	}
	
	public ParserRule getCountryRule() {
		return getCountryAccess().getRule();
	}
	
	//ResourcesConfig returns ResourcesConfig:
	//    '('
	//    (hasImage?='avec-illustration')?
	//    (hasOneStockPerSlot?='un-stock-par-ouverture')?
	//    (isConsumable?='type-consommable')?
	//    (isLoan?='emprunt-avec-retour')?
	//    (isCharged?='payant')?
	//    ')'
	//    ;
	public ResourcesConfigElements getResourcesConfigAccess() {
		return pResourcesConfig;
	}
	
	public ParserRule getResourcesConfigRule() {
		return getResourcesConfigAccess().getRule();
	}
	
	//LotsConfig returns LotsConfig:
	//    {LotsConfig} '('
	//    (hasImage?='avec-illustration')?
	//    (hasOneStockPerSlot?='un-stock-par-ouverture')?
	//    ')'
	//    ;
	public LotsConfigElements getLotsConfigAccess() {
		return pLotsConfig;
	}
	
	public ParserRule getLotsConfigRule() {
		return getLotsConfigAccess().getRule();
	}
	
	//PricingSystem returns PricingSystem:
	//    name=EString '('
	//    'devise' ':' currency=EString ','
	//    'systeme-comptable' ':' taxSystem=EString
	//    ')'
	//;
	public PricingSystemElements getPricingSystemAccess() {
		return pPricingSystem;
	}
	
	public ParserRule getPricingSystemRule() {
		return getPricingSystemAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//StatusList returns StatusList:
	//        '(' status+=Status ( "," status+=Status)* ')'
	//    ;
	public StatusListElements getStatusListAccess() {
		return pStatusList;
	}
	
	public ParserRule getStatusListRule() {
		return getStatusListAccess().getRule();
	}
	
	//Status returns Status:
	//    {Status}
	//    name=EString;
	public StatusElements getStatusAccess() {
		return pStatus;
	}
	
	public ParserRule getStatusRule() {
		return getStatusAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
