/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SServiceNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.SServiceName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cServiceconfigAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cServiceconfigServiceConfigParserRuleCall_2_0 = (RuleCall)cServiceconfigAssignment_2.eContents().get(0);
		
		//SServiceName returns ServiceName:
		//    name=EString
		//    ':'
		//    serviceconfig=ServiceConfig;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString
		//':'
		//serviceconfig=ServiceConfig
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//serviceconfig=ServiceConfig
		public Assignment getServiceconfigAssignment_2() { return cServiceconfigAssignment_2; }
		
		//ServiceConfig
		public RuleCall getServiceconfigServiceConfigParserRuleCall_2_0() { return cServiceconfigServiceConfigParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ServiceConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ServiceConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cClosesOnPublicHolidaysAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cClosesOnPublicHolidaysClosesOnPublicHolidaysKeyword_0_0 = (Keyword)cClosesOnPublicHolidaysAssignment_0.eContents().get(0);
		private final Assignment cInventoryIsPublicAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cInventoryIsPublicInventoryIsPublicKeyword_1_0 = (Keyword)cInventoryIsPublicAssignment_1.eContents().get(0);
		private final Assignment cHasChartAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasChartHasChartKeyword_2_0 = (Keyword)cHasChartAssignment_2.eContents().get(0);
		private final Assignment cCountInBusinessDaysAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cCountInBusinessDaysCountInBusinessDaysKeyword_3_0 = (Keyword)cCountInBusinessDaysAssignment_3.eContents().get(0);
		private final Keyword cCountryKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCountryAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCountryCountryParserRuleCall_6_0 = (RuleCall)cCountryAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCountryAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cCountryCountryParserRuleCall_7_1_0 = (RuleCall)cCountryAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPricingsystemKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cColonKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cPricingsystemAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final CrossReference cPricingsystemPricingSystemCrossReference_8_2_0 = (CrossReference)cPricingsystemAssignment_8_2.eContents().get(0);
		private final RuleCall cPricingsystemPricingSystemEStringParserRuleCall_8_2_0_1 = (RuleCall)cPricingsystemPricingSystemCrossReference_8_2_0.eContents().get(1);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cPricingsystemAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final CrossReference cPricingsystemPricingSystemCrossReference_8_3_1_0 = (CrossReference)cPricingsystemAssignment_8_3_1.eContents().get(0);
		private final RuleCall cPricingsystemPricingSystemEStringParserRuleCall_8_3_1_0_1 = (RuleCall)cPricingsystemPricingSystemCrossReference_8_3_1_0.eContents().get(1);
		private final Keyword cLangKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cLanguageAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cLanguageLanguageParserRuleCall_11_0 = (RuleCall)cLanguageAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cLanguageAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cLanguageLanguageParserRuleCall_12_1_0 = (RuleCall)cLanguageAssignment_12_1.eContents().get(0);
		private final Keyword cReservationsconfigKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cColonKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cReservationsconfigAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cReservationsconfigReservationsConfigParserRuleCall_15_0 = (RuleCall)cReservationsconfigAssignment_15.eContents().get(0);
		private final Keyword cResourcesconfigKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cColonKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cResourcesconfigAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cResourcesconfigResourcesConfigParserRuleCall_18_0 = (RuleCall)cResourcesconfigAssignment_18.eContents().get(0);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cCommaKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Assignment cResourcesconfigAssignment_19_1 = (Assignment)cGroup_19.eContents().get(1);
		private final RuleCall cResourcesconfigResourcesConfigParserRuleCall_19_1_0 = (RuleCall)cResourcesconfigAssignment_19_1.eContents().get(0);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cLotsconfigKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Keyword cColonKeyword_20_1 = (Keyword)cGroup_20.eContents().get(1);
		private final Assignment cLotsconfigAssignment_20_2 = (Assignment)cGroup_20.eContents().get(2);
		private final RuleCall cLotsconfigLotsConfigParserRuleCall_20_2_0 = (RuleCall)cLotsconfigAssignment_20_2.eContents().get(0);
		
		//ServiceConfig returns ServiceConfig:
		//    (closesOnPublicHolidays?='closesOnPublicHolidays')?
		//    (inventoryIsPublic?='inventoryIsPublic')?
		//    (hasChart?='hasChart')?
		//    (countInBusinessDays?='countInBusinessDays')?
		//    'country' ':' country+=Country ( "," country+=Country)*
		//    ('pricingsystem' ':' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )?
		//    'lang' ':' language+=Language ( "," language+=Language)*
		//    'reservationsconfig' ':' reservationsconfig=ReservationsConfig
		//    'resourcesconfig' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
		//    ('lotsconfig' ':' lotsconfig=LotsConfig)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(closesOnPublicHolidays?='closesOnPublicHolidays')?
		//(inventoryIsPublic?='inventoryIsPublic')?
		//(hasChart?='hasChart')?
		//(countInBusinessDays?='countInBusinessDays')?
		//'country' ':' country+=Country ( "," country+=Country)*
		//('pricingsystem' ':' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )?
		//'lang' ':' language+=Language ( "," language+=Language)*
		//'reservationsconfig' ':' reservationsconfig=ReservationsConfig
		//'resourcesconfig' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
		//('lotsconfig' ':' lotsconfig=LotsConfig)?
		public Group getGroup() { return cGroup; }
		
		//(closesOnPublicHolidays?='closesOnPublicHolidays')?
		public Assignment getClosesOnPublicHolidaysAssignment_0() { return cClosesOnPublicHolidaysAssignment_0; }
		
		//'closesOnPublicHolidays'
		public Keyword getClosesOnPublicHolidaysClosesOnPublicHolidaysKeyword_0_0() { return cClosesOnPublicHolidaysClosesOnPublicHolidaysKeyword_0_0; }
		
		//(inventoryIsPublic?='inventoryIsPublic')?
		public Assignment getInventoryIsPublicAssignment_1() { return cInventoryIsPublicAssignment_1; }
		
		//'inventoryIsPublic'
		public Keyword getInventoryIsPublicInventoryIsPublicKeyword_1_0() { return cInventoryIsPublicInventoryIsPublicKeyword_1_0; }
		
		//(hasChart?='hasChart')?
		public Assignment getHasChartAssignment_2() { return cHasChartAssignment_2; }
		
		//'hasChart'
		public Keyword getHasChartHasChartKeyword_2_0() { return cHasChartHasChartKeyword_2_0; }
		
		//(countInBusinessDays?='countInBusinessDays')?
		public Assignment getCountInBusinessDaysAssignment_3() { return cCountInBusinessDaysAssignment_3; }
		
		//'countInBusinessDays'
		public Keyword getCountInBusinessDaysCountInBusinessDaysKeyword_3_0() { return cCountInBusinessDaysCountInBusinessDaysKeyword_3_0; }
		
		//'country'
		public Keyword getCountryKeyword_4() { return cCountryKeyword_4; }
		
		//':'
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//country+=Country
		public Assignment getCountryAssignment_6() { return cCountryAssignment_6; }
		
		//Country
		public RuleCall getCountryCountryParserRuleCall_6_0() { return cCountryCountryParserRuleCall_6_0; }
		
		//( "," country+=Country)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//country+=Country
		public Assignment getCountryAssignment_7_1() { return cCountryAssignment_7_1; }
		
		//Country
		public RuleCall getCountryCountryParserRuleCall_7_1_0() { return cCountryCountryParserRuleCall_7_1_0; }
		
		//('pricingsystem' ':' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'pricingsystem'
		public Keyword getPricingsystemKeyword_8_0() { return cPricingsystemKeyword_8_0; }
		
		//':'
		public Keyword getColonKeyword_8_1() { return cColonKeyword_8_1; }
		
		//pricingsystem+=[PricingSystem|EString]
		public Assignment getPricingsystemAssignment_8_2() { return cPricingsystemAssignment_8_2; }
		
		//[PricingSystem|EString]
		public CrossReference getPricingsystemPricingSystemCrossReference_8_2_0() { return cPricingsystemPricingSystemCrossReference_8_2_0; }
		
		//EString
		public RuleCall getPricingsystemPricingSystemEStringParserRuleCall_8_2_0_1() { return cPricingsystemPricingSystemEStringParserRuleCall_8_2_0_1; }
		
		//( "," pricingsystem+=[PricingSystem|EString])*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//pricingsystem+=[PricingSystem|EString]
		public Assignment getPricingsystemAssignment_8_3_1() { return cPricingsystemAssignment_8_3_1; }
		
		//[PricingSystem|EString]
		public CrossReference getPricingsystemPricingSystemCrossReference_8_3_1_0() { return cPricingsystemPricingSystemCrossReference_8_3_1_0; }
		
		//EString
		public RuleCall getPricingsystemPricingSystemEStringParserRuleCall_8_3_1_0_1() { return cPricingsystemPricingSystemEStringParserRuleCall_8_3_1_0_1; }
		
		//'lang'
		public Keyword getLangKeyword_9() { return cLangKeyword_9; }
		
		//':'
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//language+=Language
		public Assignment getLanguageAssignment_11() { return cLanguageAssignment_11; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_11_0() { return cLanguageLanguageParserRuleCall_11_0; }
		
		//( "," language+=Language)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//language+=Language
		public Assignment getLanguageAssignment_12_1() { return cLanguageAssignment_12_1; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_12_1_0() { return cLanguageLanguageParserRuleCall_12_1_0; }
		
		//'reservationsconfig'
		public Keyword getReservationsconfigKeyword_13() { return cReservationsconfigKeyword_13; }
		
		//':'
		public Keyword getColonKeyword_14() { return cColonKeyword_14; }
		
		//reservationsconfig=ReservationsConfig
		public Assignment getReservationsconfigAssignment_15() { return cReservationsconfigAssignment_15; }
		
		//ReservationsConfig
		public RuleCall getReservationsconfigReservationsConfigParserRuleCall_15_0() { return cReservationsconfigReservationsConfigParserRuleCall_15_0; }
		
		//'resourcesconfig'
		public Keyword getResourcesconfigKeyword_16() { return cResourcesconfigKeyword_16; }
		
		//':'
		public Keyword getColonKeyword_17() { return cColonKeyword_17; }
		
		//resourcesconfig+=ResourcesConfig
		public Assignment getResourcesconfigAssignment_18() { return cResourcesconfigAssignment_18; }
		
		//ResourcesConfig
		public RuleCall getResourcesconfigResourcesConfigParserRuleCall_18_0() { return cResourcesconfigResourcesConfigParserRuleCall_18_0; }
		
		//( "," resourcesconfig+=ResourcesConfig)*
		public Group getGroup_19() { return cGroup_19; }
		
		//","
		public Keyword getCommaKeyword_19_0() { return cCommaKeyword_19_0; }
		
		//resourcesconfig+=ResourcesConfig
		public Assignment getResourcesconfigAssignment_19_1() { return cResourcesconfigAssignment_19_1; }
		
		//ResourcesConfig
		public RuleCall getResourcesconfigResourcesConfigParserRuleCall_19_1_0() { return cResourcesconfigResourcesConfigParserRuleCall_19_1_0; }
		
		//('lotsconfig' ':' lotsconfig=LotsConfig)?
		public Group getGroup_20() { return cGroup_20; }
		
		//'lotsconfig'
		public Keyword getLotsconfigKeyword_20_0() { return cLotsconfigKeyword_20_0; }
		
		//':'
		public Keyword getColonKeyword_20_1() { return cColonKeyword_20_1; }
		
		//lotsconfig=LotsConfig
		public Assignment getLotsconfigAssignment_20_2() { return cLotsconfigAssignment_20_2; }
		
		//LotsConfig
		public RuleCall getLotsconfigLotsConfigParserRuleCall_20_2_0() { return cLotsconfigLotsConfigParserRuleCall_20_2_0; }
	}
	public class EBooleanObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EBooleanObject");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBooleanObject returns ecore::EBooleanObject:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class LanguageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Language");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLanguageAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Language returns Language:
		//    {Language}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Language}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Language}
		public Action getLanguageAction_0() { return cLanguageAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class ReservationsConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ReservationsConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHasMoveOutCheckAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHasMoveOutCheckHasMoveOutCheckKeyword_0_0 = (Keyword)cHasMoveOutCheckAssignment_0.eContents().get(0);
		private final Assignment cHasMoveInCheckAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasMoveInCheckHasMoveInCheckKeyword_1_0 = (Keyword)cHasMoveInCheckAssignment_1.eContents().get(0);
		private final Keyword cMinRequestAdvanceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMinRequestAdvanceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMinRequestAdvanceEIntParserRuleCall_3_0 = (RuleCall)cMinRequestAdvanceAssignment_3.eContents().get(0);
		private final Keyword cMaxRequestAdvanceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMaxRequestAdvanceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMaxRequestAdvanceEIntParserRuleCall_5_0 = (RuleCall)cMaxRequestAdvanceAssignment_5.eContents().get(0);
		private final Keyword cStatuslistKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cStatuslistAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cStatuslistStatusListParserRuleCall_8_0 = (RuleCall)cStatuslistAssignment_8.eContents().get(0);
		
		//ReservationsConfig returns ReservationsConfig:
		//    hasMoveOutCheck?='hasMoveOutCheck'
		//    (hasMoveInCheck?='hasMoveInCheck')?
		//        'minRequestAdvance' minRequestAdvance=EInt
		//        'maxRequestAdvance' maxRequestAdvance=EInt
		//        'statuslist' ':' statuslist=StatusList
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//hasMoveOutCheck?='hasMoveOutCheck'
		//(hasMoveInCheck?='hasMoveInCheck')?
		//    'minRequestAdvance' minRequestAdvance=EInt
		//    'maxRequestAdvance' maxRequestAdvance=EInt
		//    'statuslist' ':' statuslist=StatusList
		public Group getGroup() { return cGroup; }
		
		//hasMoveOutCheck?='hasMoveOutCheck'
		public Assignment getHasMoveOutCheckAssignment_0() { return cHasMoveOutCheckAssignment_0; }
		
		//'hasMoveOutCheck'
		public Keyword getHasMoveOutCheckHasMoveOutCheckKeyword_0_0() { return cHasMoveOutCheckHasMoveOutCheckKeyword_0_0; }
		
		//(hasMoveInCheck?='hasMoveInCheck')?
		public Assignment getHasMoveInCheckAssignment_1() { return cHasMoveInCheckAssignment_1; }
		
		//'hasMoveInCheck'
		public Keyword getHasMoveInCheckHasMoveInCheckKeyword_1_0() { return cHasMoveInCheckHasMoveInCheckKeyword_1_0; }
		
		//'minRequestAdvance'
		public Keyword getMinRequestAdvanceKeyword_2() { return cMinRequestAdvanceKeyword_2; }
		
		//minRequestAdvance=EInt
		public Assignment getMinRequestAdvanceAssignment_3() { return cMinRequestAdvanceAssignment_3; }
		
		//EInt
		public RuleCall getMinRequestAdvanceEIntParserRuleCall_3_0() { return cMinRequestAdvanceEIntParserRuleCall_3_0; }
		
		//'maxRequestAdvance'
		public Keyword getMaxRequestAdvanceKeyword_4() { return cMaxRequestAdvanceKeyword_4; }
		
		//maxRequestAdvance=EInt
		public Assignment getMaxRequestAdvanceAssignment_5() { return cMaxRequestAdvanceAssignment_5; }
		
		//EInt
		public RuleCall getMaxRequestAdvanceEIntParserRuleCall_5_0() { return cMaxRequestAdvanceEIntParserRuleCall_5_0; }
		
		//'statuslist'
		public Keyword getStatuslistKeyword_6() { return cStatuslistKeyword_6; }
		
		//':'
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//statuslist=StatusList
		public Assignment getStatuslistAssignment_8() { return cStatuslistAssignment_8; }
		
		//StatusList
		public RuleCall getStatuslistStatusListParserRuleCall_8_0() { return cStatuslistStatusListParserRuleCall_8_0; }
	}
	public class CountryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Country");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLangKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLanguageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLanguageLanguageParserRuleCall_2_0 = (RuleCall)cLanguageAssignment_2.eContents().get(0);
		private final Keyword cPricingKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPricingsystemAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPricingsystemPricingSystemParserRuleCall_6_0 = (RuleCall)cPricingsystemAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Country returns Country:
		//    name=EString
		//        'lang' language=Language
		//        'pricing' ':' '(' pricingsystem=PricingSystem ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString
		//    'lang' language=Language
		//    'pricing' ':' '(' pricingsystem=PricingSystem ')'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'lang'
		public Keyword getLangKeyword_1() { return cLangKeyword_1; }
		
		//language=Language
		public Assignment getLanguageAssignment_2() { return cLanguageAssignment_2; }
		
		//Language
		public RuleCall getLanguageLanguageParserRuleCall_2_0() { return cLanguageLanguageParserRuleCall_2_0; }
		
		//'pricing'
		public Keyword getPricingKeyword_3() { return cPricingKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//pricingsystem=PricingSystem
		public Assignment getPricingsystemAssignment_6() { return cPricingsystemAssignment_6; }
		
		//PricingSystem
		public RuleCall getPricingsystemPricingSystemParserRuleCall_6_0() { return cPricingsystemPricingSystemParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class ResourcesConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.ResourcesConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHasImageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasImageHasImageKeyword_1_0 = (Keyword)cHasImageAssignment_1.eContents().get(0);
		private final Assignment cHasOneStockPerSlotAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0 = (Keyword)cHasOneStockPerSlotAssignment_2.eContents().get(0);
		private final Assignment cIsConsumableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cIsConsumableIsConsumableKeyword_3_0 = (Keyword)cIsConsumableAssignment_3.eContents().get(0);
		private final Assignment cIsLoanAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cIsLoanIsLoanKeyword_4_0 = (Keyword)cIsLoanAssignment_4.eContents().get(0);
		private final Assignment cIsChargedAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cIsChargedIsChargedKeyword_5_0 = (Keyword)cIsChargedAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ResourcesConfig returns ResourcesConfig:
		//    '('
		//    (hasImage?='hasImage')?
		//    (hasOneStockPerSlot?='hasOneStockPerSlot')?
		//    (isConsumable?='isConsumable')?
		//    (isLoan?='isLoan')?
		//    (isCharged?='isCharged')?
		//    ')'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'('
		//(hasImage?='hasImage')?
		//(hasOneStockPerSlot?='hasOneStockPerSlot')?
		//(isConsumable?='isConsumable')?
		//(isLoan?='isLoan')?
		//(isCharged?='isCharged')?
		//')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//(hasImage?='hasImage')?
		public Assignment getHasImageAssignment_1() { return cHasImageAssignment_1; }
		
		//'hasImage'
		public Keyword getHasImageHasImageKeyword_1_0() { return cHasImageHasImageKeyword_1_0; }
		
		//(hasOneStockPerSlot?='hasOneStockPerSlot')?
		public Assignment getHasOneStockPerSlotAssignment_2() { return cHasOneStockPerSlotAssignment_2; }
		
		//'hasOneStockPerSlot'
		public Keyword getHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0() { return cHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0; }
		
		//(isConsumable?='isConsumable')?
		public Assignment getIsConsumableAssignment_3() { return cIsConsumableAssignment_3; }
		
		//'isConsumable'
		public Keyword getIsConsumableIsConsumableKeyword_3_0() { return cIsConsumableIsConsumableKeyword_3_0; }
		
		//(isLoan?='isLoan')?
		public Assignment getIsLoanAssignment_4() { return cIsLoanAssignment_4; }
		
		//'isLoan'
		public Keyword getIsLoanIsLoanKeyword_4_0() { return cIsLoanIsLoanKeyword_4_0; }
		
		//(isCharged?='isCharged')?
		public Assignment getIsChargedAssignment_5() { return cIsChargedAssignment_5; }
		
		//'isCharged'
		public Keyword getIsChargedIsChargedKeyword_5_0() { return cIsChargedIsChargedKeyword_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class LotsConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.LotsConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLotsConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cHasImageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasImageHasImageKeyword_1_0 = (Keyword)cHasImageAssignment_1.eContents().get(0);
		private final Assignment cHasOneStockPerSlotAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0 = (Keyword)cHasOneStockPerSlotAssignment_2.eContents().get(0);
		
		//LotsConfig returns LotsConfig:
		//    {LotsConfig}
		//    (hasImage?='hasImage')?
		//    (hasOneStockPerSlot?='hasOneStockPerSlot')?
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{LotsConfig}
		//(hasImage?='hasImage')?
		//(hasOneStockPerSlot?='hasOneStockPerSlot')?
		public Group getGroup() { return cGroup; }
		
		//{LotsConfig}
		public Action getLotsConfigAction_0() { return cLotsConfigAction_0; }
		
		//(hasImage?='hasImage')?
		public Assignment getHasImageAssignment_1() { return cHasImageAssignment_1; }
		
		//'hasImage'
		public Keyword getHasImageHasImageKeyword_1_0() { return cHasImageHasImageKeyword_1_0; }
		
		//(hasOneStockPerSlot?='hasOneStockPerSlot')?
		public Assignment getHasOneStockPerSlotAssignment_2() { return cHasOneStockPerSlotAssignment_2; }
		
		//'hasOneStockPerSlot'
		public Keyword getHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0() { return cHasOneStockPerSlotHasOneStockPerSlotKeyword_2_0; }
	}
	public class PricingSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.PricingSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCurrencyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCurrencyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCurrencyEStringParserRuleCall_3_0 = (RuleCall)cCurrencyAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cTaxSystemKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTaxSystemAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTaxSystemEStringParserRuleCall_6_0 = (RuleCall)cTaxSystemAssignment_6.eContents().get(0);
		
		//PricingSystem returns PricingSystem:
		//    name=EString ':'
		//    'currency' currency=EString ','
		//    'taxSystem' taxSystem=EString
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString ':'
		//'currency' currency=EString ','
		//'taxSystem' taxSystem=EString
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'currency'
		public Keyword getCurrencyKeyword_2() { return cCurrencyKeyword_2; }
		
		//currency=EString
		public Assignment getCurrencyAssignment_3() { return cCurrencyAssignment_3; }
		
		//EString
		public RuleCall getCurrencyEStringParserRuleCall_3_0() { return cCurrencyEStringParserRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//'taxSystem'
		public Keyword getTaxSystemKeyword_5() { return cTaxSystemKeyword_5; }
		
		//taxSystem=EString
		public Assignment getTaxSystemAssignment_6() { return cTaxSystemAssignment_6; }
		
		//EString
		public RuleCall getTaxSystemEStringParserRuleCall_6_0() { return cTaxSystemEStringParserRuleCall_6_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class StatusListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.StatusList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStatusAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStatusStatusParserRuleCall_1_0 = (RuleCall)cStatusAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cStatusAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cStatusStatusParserRuleCall_2_1_0 = (RuleCall)cStatusAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//StatusList returns StatusList:
		//        '(' status+=Status ( "," status+=Status)* ')'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' status+=Status ( "," status+=Status)* ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//status+=Status
		public Assignment getStatusAssignment_1() { return cStatusAssignment_1; }
		
		//Status
		public RuleCall getStatusStatusParserRuleCall_1_0() { return cStatusStatusParserRuleCall_1_0; }
		
		//( "," status+=Status)*
		public Group getGroup_2() { return cGroup_2; }
		
		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//status+=Status
		public Assignment getStatusAssignment_2_1() { return cStatusAssignment_2_1; }
		
		//Status
		public RuleCall getStatusStatusParserRuleCall_2_1_0() { return cStatusStatusParserRuleCall_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class StatusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mde.pauline.metaheres.My.Status");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStatusAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Status returns Status:
		//    {Status}
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Status}
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Status}
		public Action getStatusAction_0() { return cStatusAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	
	
	private final SServiceNameElements pSServiceName;
	private final EStringElements pEString;
	private final ServiceConfigElements pServiceConfig;
	private final EBooleanObjectElements pEBooleanObject;
	private final LanguageElements pLanguage;
	private final ReservationsConfigElements pReservationsConfig;
	private final CountryElements pCountry;
	private final ResourcesConfigElements pResourcesConfig;
	private final LotsConfigElements pLotsConfig;
	private final PricingSystemElements pPricingSystem;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final StatusListElements pStatusList;
	private final StatusElements pStatus;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSServiceName = new SServiceNameElements();
		this.pEString = new EStringElements();
		this.pServiceConfig = new ServiceConfigElements();
		this.pEBooleanObject = new EBooleanObjectElements();
		this.pLanguage = new LanguageElements();
		this.pReservationsConfig = new ReservationsConfigElements();
		this.pCountry = new CountryElements();
		this.pResourcesConfig = new ResourcesConfigElements();
		this.pLotsConfig = new LotsConfigElements();
		this.pPricingSystem = new PricingSystemElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pStatusList = new StatusListElements();
		this.pStatus = new StatusElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mde.pauline.metaheres.My".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SServiceName returns ServiceName:
	//    name=EString
	//    ':'
	//    serviceconfig=ServiceConfig;
	public SServiceNameElements getSServiceNameAccess() {
		return pSServiceName;
	}
	
	public ParserRule getSServiceNameRule() {
		return getSServiceNameAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ServiceConfig returns ServiceConfig:
	//    (closesOnPublicHolidays?='closesOnPublicHolidays')?
	//    (inventoryIsPublic?='inventoryIsPublic')?
	//    (hasChart?='hasChart')?
	//    (countInBusinessDays?='countInBusinessDays')?
	//    'country' ':' country+=Country ( "," country+=Country)*
	//    ('pricingsystem' ':' pricingsystem+=[PricingSystem|EString] ( "," pricingsystem+=[PricingSystem|EString])* )?
	//    'lang' ':' language+=Language ( "," language+=Language)*
	//    'reservationsconfig' ':' reservationsconfig=ReservationsConfig
	//    'resourcesconfig' ':' resourcesconfig+=ResourcesConfig ( "," resourcesconfig+=ResourcesConfig)*
	//    ('lotsconfig' ':' lotsconfig=LotsConfig)?
	//;
	public ServiceConfigElements getServiceConfigAccess() {
		return pServiceConfig;
	}
	
	public ParserRule getServiceConfigRule() {
		return getServiceConfigAccess().getRule();
	}
	
	//EBooleanObject returns ecore::EBooleanObject:
	//    'true' | 'false';
	public EBooleanObjectElements getEBooleanObjectAccess() {
		return pEBooleanObject;
	}
	
	public ParserRule getEBooleanObjectRule() {
		return getEBooleanObjectAccess().getRule();
	}
	
	//Language returns Language:
	//    {Language}
	//    name=EString;
	public LanguageElements getLanguageAccess() {
		return pLanguage;
	}
	
	public ParserRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}
	
	//ReservationsConfig returns ReservationsConfig:
	//    hasMoveOutCheck?='hasMoveOutCheck'
	//    (hasMoveInCheck?='hasMoveInCheck')?
	//        'minRequestAdvance' minRequestAdvance=EInt
	//        'maxRequestAdvance' maxRequestAdvance=EInt
	//        'statuslist' ':' statuslist=StatusList
	//    ;
	public ReservationsConfigElements getReservationsConfigAccess() {
		return pReservationsConfig;
	}
	
	public ParserRule getReservationsConfigRule() {
		return getReservationsConfigAccess().getRule();
	}
	
	//Country returns Country:
	//    name=EString
	//        'lang' language=Language
	//        'pricing' ':' '(' pricingsystem=PricingSystem ')'
	//;
	public CountryElements getCountryAccess() {
		return pCountry;
	}
	
	public ParserRule getCountryRule() {
		return getCountryAccess().getRule();
	}
	
	//ResourcesConfig returns ResourcesConfig:
	//    '('
	//    (hasImage?='hasImage')?
	//    (hasOneStockPerSlot?='hasOneStockPerSlot')?
	//    (isConsumable?='isConsumable')?
	//    (isLoan?='isLoan')?
	//    (isCharged?='isCharged')?
	//    ')'
	//    ;
	public ResourcesConfigElements getResourcesConfigAccess() {
		return pResourcesConfig;
	}
	
	public ParserRule getResourcesConfigRule() {
		return getResourcesConfigAccess().getRule();
	}
	
	//LotsConfig returns LotsConfig:
	//    {LotsConfig}
	//    (hasImage?='hasImage')?
	//    (hasOneStockPerSlot?='hasOneStockPerSlot')?
	//    ;
	public LotsConfigElements getLotsConfigAccess() {
		return pLotsConfig;
	}
	
	public ParserRule getLotsConfigRule() {
		return getLotsConfigAccess().getRule();
	}
	
	//PricingSystem returns PricingSystem:
	//    name=EString ':'
	//    'currency' currency=EString ','
	//    'taxSystem' taxSystem=EString
	//;
	public PricingSystemElements getPricingSystemAccess() {
		return pPricingSystem;
	}
	
	public ParserRule getPricingSystemRule() {
		return getPricingSystemAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//StatusList returns StatusList:
	//        '(' status+=Status ( "," status+=Status)* ')'
	//    ;
	public StatusListElements getStatusListAccess() {
		return pStatusList;
	}
	
	public ParserRule getStatusListRule() {
		return getStatusListAccess().getRule();
	}
	
	//Status returns Status:
	//    {Status}
	//    name=EString;
	public StatusElements getStatusAccess() {
		return pStatus;
	}
	
	public ParserRule getStatusRule() {
		return getStatusAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
