/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyStandaloneSetup extends MyStandaloneSetupGenerated {

	public static void doSetup() {
		new MyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
