/*
 * generated by Xtext 2.27.0
 */
package mde.pauline.metaheres.parser.antlr;

import com.google.inject.Inject;
import mde.pauline.metaheres.parser.antlr.internal.InternalMyParser;
import mde.pauline.metaheres.services.MyGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyParser extends AbstractAntlrParser {

	@Inject
	private MyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyParser createParser(XtextTokenStream stream) {
		return new InternalMyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SServiceName";
	}

	public MyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
